apiVersion: v2
appVersion: v0.3.1
description: |
    Hajimari is a beautiful & customizable browser startpage/dashboard with 
    Kubernetes application discovery
name: hajimari
version: 2.0.2
kubeVersion: ">=1.16.0-0"
keywords:
- hajimari
- startpage
- dashboard
home: https://github.com/ullbergm/hajimari/tree/master/charts/hajimari
icon: https://raw.githubusercontent.com/ullbergm/hajimari/main/assets/logo.png
sources:
- https://github.com/ullbergm/hajimari
maintainers:
- name: ullbergm
  email: ullbergm@users.noreply.github.com
dependencies:
- name: common
  version: 0.2.2
  repository: https://bjw-s.github.io/helm-charts/