{{- if .Values.createCRAppSample }}

apiVersion: hajimari.io/v1alpha1
kind: Application
metadata:
  name: hajimari-issues
spec:
  name: Hajimari Issues
  group: info
  icon: simple-icons:github
  url: https://github.com/ullbergm/hajimari/issues
  info: Submit issue to this project
  targetBlank: true

{{- end }}
