{{- include "common.values.setup" . }}

{{- define "hajimari.settingsVolume" -}}
enabled: "true"
mountPath: "/config/config.yaml"
subPath: "config.yaml"
type: "custom"
volumeSpec:
  configMap:
    name: {{ include "common.names.fullname" . }}-settings
{{- end -}}
{{- $_ := set .Values.persistence "hajimari-settings" (include "hajimari.settingsVolume" . | fromYaml) -}}

{{ include "common.all" . }}